export const ActionTypes = {
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    FETCH_TASKS: 'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
}